import test from 'node:test';
import assert from 'node:assert/strict';
import {parseAnlz,bucketMax,PreviewCache,syntheticTracks} from '../web/core.mjs';
function section(tag,payload,header=20){const b=Buffer.alloc(header+payload.length);b.write(tag);b.writeUInt32BE(header,4);b.writeUInt32BE(b.length,8);if(header>=16)b.writeUInt32BE(payload.length,12);payload.copy(b,header);return b;}
function file(...tags){const b=Buffer.alloc(28);b.write('PMAI');b.writeUInt32BE(28,4);b.writeUInt32BE(28+tags.reduce((n,t)=>n+t.length,0),8);return Buffer.concat([b,...tags]);}
const pwav=()=>section('PWAV',Buffer.from(Array.from({length:400},(_,i)=>i%256)));
test('PWAV masks all shade combinations and honors Buffer byte offset',()=>{const p=file(pwav()),b=Buffer.concat([Buffer.alloc(7),p]);const r=parseAnlz(b.subarray(7));assert.equal(r.heights.length,400);assert.deepEqual([...r.heights],Array.from({length:400},(_,i)=>i%32));});
test('unknown tags skip; PPTH UTF16BE decodes diacritics',()=>{const p=Buffer.from('/Muzică/Piesă.wav\0','utf16le').swap16();const r=parseAnlz(file(section('ZZZZ',Buffer.from([1,2]),12),section('PPTH',p,16),pwav()));assert.equal(r.path,'/Muzică/Piesă.wav');assert.equal(r.tags.length,3);});
test('missing PWAV is explicit',()=>assert.equal(parseAnlz(file()).heights,null));
test('reject corruption, truncation, duplicates and wrong column counts',()=>{const cases=[Buffer.alloc(8),file(pwav()).subarray(0,-1),file(pwav(),pwav()),file(section('PWAV',Buffer.alloc(399)))];const bad=file(pwav());bad.writeUInt32BE(0,28+8);cases.push(bad);const tooLong=file(pwav());tooLong.writeUInt32BE(0xffffffff,28+8);cases.push(tooLong);const h=file(pwav());h.writeUInt32BE(12,32);cases.push(h);for(const c of cases)assert.throws(()=>parseAnlz(c));});
test('every transient survives at 80/110/140 including last source column',()=>{for(const w of [80,110,140])for(let i=0;i<400;i++){const v=new Uint8Array(400);v[i]=31;const out=bucketMax(v,w);assert.equal(out.length,w);assert.equal(out.reduce((s,v)=>s+v,0),31);}});
test('bucket maximum has known expected values, zero remains zero',()=>{assert.deepEqual([...bucketMax([0,2,31,1,4,5],3)],[2,31,5]);assert.deepEqual([...bucketMax(new Uint8Array(400),80)],Array(80).fill(0));for(const w of [0,401,2.5])assert.throws(()=>bucketMax(new Uint8Array(400),w));assert.throws(()=>bucketMax([32],1));});
test('cache is bounded LRU and keyed by content and width',()=>{const c=new PreviewCache(2),h=new Uint8Array(400);const a=c.prepare('a',h,80);assert.equal(c.prepare('a',h,80),a);c.prepare('a',h,110);c.prepare('a',h,80);c.prepare('b',h,80);assert.equal(c.items.size,2);assert.equal(c.items.has('a:110'),false);assert.equal(c.hits,2);});
test('synthetic input is deterministic, labeled, and distinct',()=>{assert.deepEqual(syntheticTracks(),syntheticTracks());assert.equal(syntheticTracks().length,40);assert.equal(syntheticTracks()[0].source,'SYNTHETIC');assert.notDeepEqual(syntheticTracks()[0].heights,syntheticTracks()[1].heights);});
